/**
 * LocalStorage manager and sample demo data for Wildlife Monitoring Application
 */

const STORAGE_KEY = 'wildlife_manager_data_v5';

export async function forceClearAllCache() {
  try {
    localStorage.clear();
    sessionStorage.clear();

    if ('caches' in window) {
      const keys = await caches.keys();
      await Promise.all(keys.map((key) => caches.delete(key)));
    }

    if ('serviceWorker' in navigator) {
      const registrations = await navigator.serviceWorker.getRegistrations();
      for (const reg of registrations) {
        await reg.unregister();
      }
    }
  } catch (err) {
    console.warn('Error clearing browser cache:', err);
  }

  window.location.href = window.location.origin + window.location.pathname + '?resetCache=' + Date.now();
}

export const INITIAL_FACILITY_INFO = {
  facilityName: 'Cơ sở Nuôi Sinh sản Động vật Hoang dã Xanh',
  ownerName: 'Nguyễn Văn A',
  registrationCode: 'CSNSS-2026-088/KL',
  address: 'Xã Phú Lý, Huyện Vĩnh Cửu, Tỉnh Đồng Nai',
  phone: '0912 345 678',
  purposeCode: 'T', // Default Thương mại
};

export const INITIAL_SPECIES_LIST = [
  {
    id: 'species_1',
    vietnameseName: 'Hổ Đông Dương',
    scientificName: 'Panthera tigris corbetti',
    group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IB)',
    citesAppendix: 'Phụ lục I CITES',
    purposeCode: 'C', // Bảo tồn / Vườn thú
    baseline: {
      date: '2026-01-01',
      father: 2,
      mother: 3,
      otherMale: 1,
      otherFemale: 2,
      otherUnknown: 0,
      note: 'Hiện trạng vật nuôi ghi nhận đầu năm 2026',
      verifier: 'Hạt Kiểm lâm Vĩnh Cửu',
    },
    fluctuations: [
      {
        id: 'fluc_1',
        date: '2026-01-15',
        time: '08:30',
        incFather: 0,
        incMother: 0,
        incOtherMale: 0,
        incOtherFemale: 0,
        incOtherUnknown: 2,
        decFather: 0,
        decMother: 0,
        decOtherMale: 0,
        decOtherFemale: 0,
        decOtherUnknown: 0,
        reason: 'Sinh sản thành công 02 cá thể hổ con thế hệ F1',
        purpose: 'C',
        verifier: 'Đã xác nhận kiểm lâm',
        createdAt: 1768437000000,
      },
      {
        id: 'fluc_2',
        date: '2026-03-10',
        time: '14:00',
        incFather: 0,
        incMother: 1,
        incOtherMale: 0,
        incOtherFemale: 0,
        incOtherUnknown: 0,
        decFather: 0,
        decMother: 0,
        decOtherMale: 0,
        decOtherFemale: 0,
        decOtherUnknown: 0,
        reason: 'Nhập ghép đàn 01 cá thể cái trưởng thành từ Thảo Thảo Vườn Thú B',
        purpose: 'Z',
        verifier: 'Hạt Kiểm lâm Vĩnh Cửu',
        createdAt: 1773136800000,
      },
      {
        id: 'fluc_3',
        date: '2026-05-05',
        time: '09:15',
        incFather: 0,
        incMother: 0,
        incOtherMale: 1,
        incOtherFemale: 1,
        incOtherUnknown: 0,
        decFather: 0,
        decMother: 0,
        decOtherMale: 0,
        decOtherFemale: 0,
        decOtherUnknown: 2,
        reason: 'Xác định giới tính 02 hổ con thế hệ F1 (01 đực, 01 cái)',
        purpose: 'C',
        verifier: 'Kiểm lâm địa phương',
        createdAt: 1777972500000,
      },
      {
        id: 'fluc_4',
        date: '2026-06-20',
        time: '10:00',
        incFather: 0,
        incMother: 0,
        incOtherMale: 0,
        incOtherFemale: 0,
        incOtherUnknown: 0,
        decFather: 0,
        decMother: 0,
        decOtherMale: 0,
        decOtherFemale: 1,
        decOtherUnknown: 0,
        reason: 'Chuyển nhượng/Tặng cho Trung tâm Cứu hộ theo QĐ số 45/QĐ-KL',
        purpose: 'R',
        verifier: 'Chi cục Kiểm lâm Đồng Nai',
        createdAt: 1781949600000,
      },
    ],
  },
  {
    id: 'species_2',
    vietnameseName: 'Trăn đất',
    scientificName: 'Python bivittatus',
    group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
    citesAppendix: 'Phụ lục II CITES',
    purposeCode: 'T', // Thương mại
    baseline: {
      date: '2026-01-01',
      father: 5,
      mother: 10,
      otherMale: 4,
      otherFemale: 6,
      otherUnknown: 15,
      note: 'Số lượng vật nuôi hiện có tại trại',
      verifier: 'Hạt Kiểm lâm địa phương',
    },
    fluctuations: [
      {
        id: 'fluc_201',
        date: '2026-02-20',
        time: '09:00',
        incFather: 0,
        incMother: 0,
        incOtherMale: 0,
        incOtherFemale: 0,
        incOtherUnknown: 30,
        decFather: 0,
        decMother: 0,
        decOtherMale: 0,
        decOtherFemale: 0,
        decOtherUnknown: 0,
        reason: 'Sinh sản 30 trăn con lứa F1 nở ngày 20/02/2026',
        purpose: 'T',
        verifier: 'Đã xác nhận',
        createdAt: 1771578000000,
      },
      {
        id: 'fluc_202',
        date: '2026-04-15',
        time: '15:30',
        incFather: 0,
        incMother: 0,
        incOtherMale: 0,
        incOtherFemale: 0,
        incOtherUnknown: 0,
        decFather: 0,
        decMother: 0,
        decOtherMale: 0,
        decOtherFemale: 0,
        decOtherUnknown: 10,
        reason: 'Xuất bán 10 trăn giống con cho Cơ sở nuôi trồng C (Căn cứ HĐ số 12)',
        purpose: 'T',
        verifier: 'Hạt Kiểm lâm xác nhận',
        createdAt: 1776241800000,
      },
    ],
  },
];

export const EMPTY_FACILITY_INFO = {
  facilityName: '',
  ownerName: '',
  registrationCode: '',
  address: '',
  phone: '',
  purposeCode: 'T',
};

export const REAL_FACILITIES_DATA = [
  {
    id: 'fac_1',
    facilityName: 'Cơ sở nuôi Lê Thị Xuân',
    ownerName: 'Lê Thị Xuân',
    registrationCode: 'IIB-DLC-027',
    registrationDate: '2023-03-17',
    commune: 'xã Hòa Sơn',
    address: 'Thôn 3, xã Hòa Sơn, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_1_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2023-03-17',
          father: 4,
          mother: 5,
          otherMale: 8,
          otherFemale: 10,
          otherUnknown: 2,
          note: 'Số lượng vật nuôi theo chứng nhận cơ sở',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_2',
    facilityName: 'Cơ sở nuôi Nguyễn Văn Thúy',
    ownerName: 'Nguyễn Văn Thúy',
    registrationCode: 'IIB-C-DLC-028',
    registrationDate: '2023-04-17',
    commune: 'xã Hòa Sơn',
    address: 'Thôn Quảng Đông, xã Hòa Sơn, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_2_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2023-04-17',
          father: 2,
          mother: 3,
          otherMale: 6,
          otherFemale: 7,
          otherUnknown: 3,
          note: 'Số lượng vật nuôi đăng ký',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_3',
    facilityName: 'Cơ sở nuôi Trịnh Viết Long',
    ownerName: 'Trịnh Viết Long',
    registrationCode: '028-25/B-DLC',
    registrationDate: '2025-10-03',
    commune: 'xã Hòa Sơn',
    address: 'Thôn 4, xã Hòa Sơn, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: 'Nghỉ nuôi',
    speciesList: [
      {
        id: 'sp_3_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2025-10-03',
          father: 0,
          mother: 0,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Cơ sở hiện nghỉ nuôi',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_4',
    facilityName: 'Cơ sở nuôi Phạm Bá Quang',
    ownerName: 'Phạm Bá Quang',
    registrationCode: 'Chưa có mã số',
    registrationDate: '',
    commune: 'xã Hòa Sơn',
    address: 'Thôn 3, xã Hòa Sơn, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: 'Chưa có mã số',
    speciesList: [
      {
        id: 'sp_4_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 4,
          mother: 11,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Chưa được cấp mã số cơ sở',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_5',
    facilityName: 'Cơ sở nuôi Phan Thanh Hùng',
    ownerName: 'Phan Thanh Hùng',
    registrationCode: 'IIB-DLC-021',
    registrationDate: '2022-04-22',
    commune: 'xã Hòa Sơn',
    address: 'Thôn 1, xã Hòa Sơn, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: 'Nghỉ nuôi',
    speciesList: [
      {
        id: 'sp_5_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2022-04-22',
          father: 0,
          mother: 0,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Cơ sở nghỉ nuôi',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_6',
    facilityName: 'Cơ sở nuôi Lê Nguyễn Nhật Tân',
    ownerName: 'Lê Nguyễn Nhật Tân',
    registrationCode: 'IIB-DLC-025',
    registrationDate: '',
    commune: 'xã Hòa Sơn',
    address: 'Thôn 6, xã Hòa Sơn, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: 'Nghỉ nuôi',
    speciesList: [
      {
        id: 'sp_6_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 0,
          mother: 0,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Cơ sở nghỉ nuôi',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_7',
    facilityName: 'Cơ sở nuôi Nguyễn Tấn Danh Nhân',
    ownerName: 'Nguyễn Tấn Danh Nhân',
    registrationCode: 'IIB-C-DLC-055',
    registrationDate: '2024-07-03',
    commune: 'xã Yang Mao',
    address: 'Buôn Tơ Rang, xã Yang Mao, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_7_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2024-07-03',
          father: 3,
          mother: 5,
          otherMale: 12,
          otherFemale: 14,
          otherUnknown: 19,
          note: 'Số lượng Cầy vòi Hương hiện có',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
      {
        id: 'sp_7_2',
        vietnameseName: 'Cầy vòi mốc',
        scientificName: 'Paguma larvata',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2024-07-03',
          father: 2,
          mother: 3,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Cầy vòi mốc hiện có',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
      {
        id: 'sp_7_3',
        vietnameseName: 'Don',
        scientificName: 'Atherurus macrourus',
        group: 'Động vật rừng (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 1,
          mother: 1,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Hiện trạng nuôi loài Don',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
      {
        id: 'sp_7_4',
        vietnameseName: 'Nhím',
        scientificName: 'Hystrix brachyura',
        group: 'Động vật rừng thông thường',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 6,
          mother: 12,
          otherMale: 21,
          otherFemale: 31,
          otherUnknown: 11,
          note: 'Hiện trạng nuôi loài Nhím',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_8',
    facilityName: 'Cơ sở nuôi Huỳnh Công Nam',
    ownerName: 'Huỳnh Công Nam',
    registrationCode: '53-26/B-DLC',
    registrationDate: '2026-05-05',
    commune: 'xã Yang Mao',
    address: 'Buôn chàm A, xã Yang Mao, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_8_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2026-05-05',
          father: 1,
          mother: 5,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 4,
          note: 'Hiện trạng nuôi ban đầu',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_9',
    facilityName: 'Cơ sở nuôi Trần Duy Quân',
    ownerName: 'Trần Duy Quân',
    registrationCode: '14-26/B-DLC',
    registrationDate: '2026-03-03',
    commune: 'xã Yang Mao',
    address: 'Thôn Ea Luêh, xã Yang Mao, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_9_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2026-03-03',
          father: 5,
          mother: 8,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Hiện trạng nuôi ban đầu',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_10',
    facilityName: 'Cơ sở nuôi Trịnh Lục',
    ownerName: 'Trịnh Lục',
    registrationCode: '52-26/B-DLC',
    registrationDate: '2026-05-08',
    commune: 'xã Cư Pui',
    address: 'Thôn 3, xã Cư Pui, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_10_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2026-05-08',
          father: 2,
          mother: 3,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Hiện trạng nuôi ban đầu',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_11',
    facilityName: 'Cơ sở nuôi Nguyễn Hữu Đô',
    ownerName: 'Nguyễn Hữu Đô',
    registrationCode: 'IIB-C-DLC-063',
    registrationDate: '2024-09-25',
    commune: 'xã Cư Pui',
    address: 'Thôn 3, xã Cư Pui, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_11_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2024-09-25',
          father: 4,
          mother: 7,
          otherMale: 5,
          otherFemale: 16,
          otherUnknown: 19,
          note: 'Hiện trạng nuôi đăng ký',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_12',
    facilityName: 'Cơ sở nuôi Lê Thanh Đức',
    ownerName: 'Lê Thanh Đức',
    registrationCode: 'IIB-C-DLC-060',
    registrationDate: '2024-09-06',
    commune: 'Xã Krông Bông',
    address: 'Thôn 5, Xã Krông Bông, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_12_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2024-09-06',
          father: 2,
          mother: 7,
          otherMale: 11,
          otherFemale: 9,
          otherUnknown: 6,
          note: 'Hiện trạng nuôi đăng ký',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_13',
    facilityName: 'Cơ sở nuôi Ngô Thị Trang',
    ownerName: 'Ngô Thị Trang',
    registrationCode: '010-25/B-DLC',
    registrationDate: '2025-07-31',
    commune: 'Xã Krông Bông',
    address: 'Thôn 8, Xã Krông Bông, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_13_1',
        vietnameseName: 'Cầy vòi Hương',
        scientificName: 'Paradoxurus hermaphroditus',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2025-07-31',
          father: 6,
          mother: 7,
          otherMale: 7,
          otherFemale: 10,
          otherUnknown: 7,
          note: 'Hiện trạng nuôi đăng ký',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_14',
    facilityName: 'Cơ sở nuôi Hà Huy Thanh',
    ownerName: 'Hà Huy Thanh',
    registrationCode: '18-26/B-DLC',
    registrationDate: '2026-03-17',
    commune: 'Xã Krông Bông',
    address: 'TDP4, Xã Krông Bông, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_14_1',
        vietnameseName: 'Cầy vòi mốc',
        scientificName: 'Paguma larvata',
        group: 'Động vật rừng nguy cấp, quý, hiếm (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2026-03-17',
          father: 5,
          mother: 23,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Hiện trạng nuôi đăng ký',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
      {
        id: 'sp_14_2',
        vietnameseName: 'Dúi má đào',
        scientificName: 'Rhizomys sumatrensis',
        group: 'Động vật rừng (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 9,
          mother: 34,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Hiện trạng nuôi loài Dúi má đào',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_15',
    facilityName: 'Cơ sở nuôi Trần Văn Tới',
    ownerName: 'Trần Văn Tới',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'xã Yang Mao',
    address: 'Thôn 1, xã Yang Mao, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_15_1',
        vietnameseName: 'Dúi mốc lớn',
        scientificName: 'Rhizomys pruinosus',
        group: 'Động vật rừng thông thường',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 9,
          mother: 9,
          otherMale: 28,
          otherFemale: 45,
          otherUnknown: 47,
          note: 'Số lượng Dúi mốc lớn hiện có',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_16',
    facilityName: 'Cơ sở nuôi Lê Đình Tâm',
    ownerName: 'Lê Đình Tâm',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'xã Yang Mao',
    address: 'Thôn Cư Drăm, xã Yang Mao, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_16_1',
        vietnameseName: 'Dúi mốc lớn',
        scientificName: 'Rhizomys pruinosus',
        group: 'Động vật rừng thông thường',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 2,
          mother: 2,
          otherMale: 4,
          otherFemale: 6,
          otherUnknown: 0,
          note: 'Số lượng Dúi mốc lớn hiện có',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_17',
    facilityName: 'Cơ sở nuôi Nguyễn Kim Danh',
    ownerName: 'Nguyễn Kim Danh',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'xã Yang Mao',
    address: 'Buôn Tul, xã Yang Mao, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_17_1',
        vietnameseName: 'Dúi mốc lớn',
        scientificName: 'Rhizomys pruinosus',
        group: 'Động vật rừng thông thường',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 2,
          mother: 10,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Dúi mốc lớn hiện có',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_18',
    facilityName: 'Cơ sở nuôi Lê Quang Mạnh',
    ownerName: 'Lê Quang Mạnh',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'Xã Krông Bông',
    address: 'Thôn 29, Xã Krông Bông, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_18_1',
        vietnameseName: 'Dúi má đào',
        scientificName: 'Rhizomys sumatrensis',
        group: 'Động vật rừng (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 3,
          mother: 4,
          otherMale: 10,
          otherFemale: 12,
          otherUnknown: 0,
          note: 'Số lượng Dúi má đào hiện có',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
      {
        id: 'sp_18_2',
        vietnameseName: 'Dúi mốc lớn',
        scientificName: 'Rhizomys pruinosus',
        group: 'Động vật rừng thông thường',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 19,
          mother: 61,
          otherMale: 17,
          otherFemale: 15,
          otherUnknown: 58,
          note: 'Số lượng Dúi mốc lớn hiện có',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_19',
    facilityName: 'Cơ sở nuôi Nguyễn Trương Đắc Nam',
    ownerName: 'Nguyễn Trương Đắc Nam',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'Xã Krông Bông',
    address: 'Thôn 9, Xã Krông Bông, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_19_1',
        vietnameseName: 'Dúi mốc lớn',
        scientificName: 'Rhizomys pruinosus',
        group: 'Động vật rừng thông thường',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 10,
          mother: 15,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Dúi mốc lớn hiện có',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_20',
    facilityName: 'Cơ sở nuôi Trần Văn Lực',
    ownerName: 'Trần Văn Lực',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'Xã Dang Kang',
    address: 'Buôn Cư Ênun A, Xã Dang Kang, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_20_1',
        vietnameseName: 'Dúi má đào',
        scientificName: 'Rhizomys sumatrensis',
        group: 'Động vật rừng (Nhóm IIB)',
        citesAppendix: 'Phụ lục II CITES',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 4,
          mother: 26,
          otherMale: 6,
          otherFemale: 8,
          otherUnknown: 11,
          note: 'Số lượng Dúi má đào hiện có',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_21',
    facilityName: 'Cơ sở nuôi Đinh Tiến Toàn',
    ownerName: 'Đinh Tiến Toàn',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'Xã Dang Kang',
    address: 'Thôn 3, Xã Dang Kang, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_21_1',
        vietnameseName: 'Dúi mốc lớn',
        scientificName: 'Rhizomys pruinosus',
        group: 'Động vật rừng thông thường',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 10,
          mother: 10,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Dúi mốc lớn hiện có',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_22',
    facilityName: 'Cơ sở nuôi Nguyễn Thanh',
    ownerName: 'Nguyễn Thanh',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'xã Hòa Sơn',
    address: 'Thôn 2, xã Hòa Sơn, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_22_1',
        vietnameseName: 'Chim Cu gáy',
        scientificName: 'Streptopelia Chinensis',
        group: 'Động vật rừng thông thường (Chim)',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 1,
          mother: 1,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Chim Cu gáy nuôi',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_23',
    facilityName: 'Cơ sở nuôi Huỳnh Phúc Lợi',
    ownerName: 'Huỳnh Phúc Lợi',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'xã Hòa Sơn',
    address: 'Thôn 2, xã Hòa Sơn, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'O',
    note: 'Làm cảnh',
    speciesList: [
      {
        id: 'sp_23_1',
        vietnameseName: 'Chim Chào mào',
        scientificName: 'Pycnonotus Jocosus',
        group: 'Động vật rừng thông thường (Chim)',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'O',
        baseline: {
          date: '2026-01-01',
          father: 3,
          mother: 0,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Chim Chào mào nuôi cảnh',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_24',
    facilityName: 'Cơ sở nuôi Phan Thanh Trúc',
    ownerName: 'Phan Thanh Trúc',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'xã Hòa Sơn',
    address: 'Thôn 4, xã Hòa Sơn, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_24_1',
        vietnameseName: 'Chim Chào mào',
        scientificName: 'Pycnonotus Jocosus',
        group: 'Động vật rừng thông thường (Chim)',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 5,
          mother: 5,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Chim Chào mào nuôi',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_25',
    facilityName: 'Cơ sở nuôi Thái Hồng Sơn',
    ownerName: 'Thái Hồng Sơn',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'Xã Krông Bông',
    address: 'Thôn 4, Xã Krông Bông, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_25_1',
        vietnameseName: 'Chim Chào mào',
        scientificName: 'Pycnonotus Jocosus',
        group: 'Động vật rừng thông thường (Chim)',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 5,
          mother: 5,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Chim Chào mào nuôi',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_26',
    facilityName: 'Cơ sở nuôi Nguyễn Trí',
    ownerName: 'Nguyễn Trí',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'Xã Krông Bông',
    address: 'Thôn 7, Xã Krông Bông, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_26_1',
        vietnameseName: 'Chim Cu gáy',
        scientificName: 'Streptopelia Chinensis',
        group: 'Động vật rừng thông thường (Chim)',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 11,
          mother: 11,
          otherMale: 1,
          otherFemale: 1,
          otherUnknown: 0,
          note: 'Số lượng Chim Cu gáy nuôi',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_27',
    facilityName: 'Cơ sở nuôi Nguyễn Văn Hòa',
    ownerName: 'Nguyễn Văn Hòa',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'Xã Krông Bông',
    address: 'Thôn 2, Xã Krông Bông, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_27_1',
        vietnameseName: 'Chim Chào mào',
        scientificName: 'Pycnonotus Jocosus',
        group: 'Động vật rừng thông thường (Chim)',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 2,
          mother: 2,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Chim Chào mào nuôi',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_28',
    facilityName: 'Cơ sở nuôi Trần Văn Hà',
    ownerName: 'Trần Văn Hà',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'Xã Krông Bông',
    address: 'Thôn 26, Xã Krông Bông, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_28_1',
        vietnameseName: 'Chim Chào mào',
        scientificName: 'Pycnonotus Jocosus',
        group: 'Động vật rừng thông thường (Chim)',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 1,
          mother: 1,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Chim Chào mào nuôi',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_29',
    facilityName: 'Cơ sở nuôi Trần Ngọc Long',
    ownerName: 'Trần Ngọc Long',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'Xã Krông Bông',
    address: 'Thôn 2, Xã Krông Bông, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_29_1',
        vietnameseName: 'Chim Cu gáy',
        scientificName: 'Streptopelia Chinensis',
        group: 'Động vật rừng thông thường (Chim)',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 2,
          mother: 2,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Chim Cu gáy nuôi',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_30',
    facilityName: 'Cơ sở nuôi Hoàng Văn Hải',
    ownerName: 'Hoàng Văn Hải',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'Xã Dang Kang',
    address: 'Thôn 6, Xã Dang Kang, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'T',
    note: '',
    speciesList: [
      {
        id: 'sp_30_1',
        vietnameseName: 'Chim Chào mào',
        scientificName: 'Pycnonotus Jocosus',
        group: 'Động vật rừng thông thường (Chim)',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'T',
        baseline: {
          date: '2026-01-01',
          father: 2,
          mother: 2,
          otherMale: 3,
          otherFemale: 2,
          otherUnknown: 3,
          note: 'Số lượng Chim Chào mào nuôi',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
  {
    id: 'fac_31',
    facilityName: 'Cơ sở nuôi Võ Văn Nhơn',
    ownerName: 'Võ Văn Nhơn',
    registrationCode: 'Đang cập nhật',
    registrationDate: '',
    commune: 'Xã Dang Kang',
    address: 'Thôn 7, Xã Dang Kang, Huyện Krông Bông, Tỉnh Đắk Lắk',
    phone: '',
    purposeCode: 'O',
    note: 'Làm cảnh',
    speciesList: [
      {
        id: 'sp_31_1',
        vietnameseName: 'Chim Chào mào',
        scientificName: 'Pycnonotus Jocosus',
        group: 'Động vật rừng thông thường (Chim)',
        citesAppendix: 'Khai báo kiểm lâm',
        purposeCode: 'O',
        baseline: {
          date: '2026-01-01',
          father: 1,
          mother: 1,
          otherMale: 0,
          otherFemale: 0,
          otherUnknown: 0,
          note: 'Số lượng Chim Chào mào nuôi cảnh',
          verifier: 'Hạt Kiểm lâm Huyện Krông Bông',
        },
        fluctuations: [],
      },
    ],
  },
];

export function clearAppData() {
  const emptyData = {
    facilitiesList: [],
    activeFacilityId: null,
    facilityInfo: { ...EMPTY_FACILITY_INFO },
    speciesList: [],
    activeSpeciesId: null,
  };
  saveAppData(emptyData);
  return emptyData;
}

export function resetToDemoData() {
  const demoData = {
    facilitiesList: REAL_FACILITIES_DATA,
    activeFacilityId: REAL_FACILITIES_DATA[0].id,
    facilityInfo: REAL_FACILITIES_DATA[0],
    speciesList: REAL_FACILITIES_DATA[0].speciesList,
    activeSpeciesId: REAL_FACILITIES_DATA[0].speciesList[0].id,
  };
  saveAppData(demoData);
  return demoData;
}

export function loadAppData() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      return resetToDemoData();
    }
    const parsed = JSON.parse(raw);

    // Force reload/merge with REAL_FACILITIES_DATA to incorporate the latest full datasets
    const facilitiesList = REAL_FACILITIES_DATA;
    const activeFacilityId = parsed.activeFacilityId || facilitiesList[0]?.id || null;
    const activeFacility = facilitiesList.find((f) => f.id === activeFacilityId) || facilitiesList[0] || null;

    const facilityInfo = activeFacility
      ? {
          id: activeFacility.id,
          facilityName: activeFacility.facilityName,
          ownerName: activeFacility.ownerName,
          registrationCode: activeFacility.registrationCode,
          registrationDate: activeFacility.registrationDate,
          address: activeFacility.address,
          phone: activeFacility.phone,
          purposeCode: activeFacility.purposeCode,
          note: activeFacility.note,
        }
      : parsed.facilityInfo || { ...EMPTY_FACILITY_INFO };

    const speciesList = activeFacility ? activeFacility.speciesList : parsed.speciesList || [];
    const activeSpeciesId = parsed.activeSpeciesId || speciesList[0]?.id || null;

    return {
      facilitiesList,
      activeFacilityId,
      facilityInfo,
      speciesList,
      activeSpeciesId,
    };
  } catch (err) {
    console.error('Failed to load local storage:', err);
    return resetToDemoData();
  }
}

export function saveAppData(data) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  } catch (err) {
    console.error('Failed to save to local storage:', err);
  }
}
